apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "resume-builder.fullname" . }}-backend-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.backend.persistence.size }}
