---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: resume-builder-cloudflared-secret
  namespace: resume-builder
spec:
  encryptedData:
    TUNNEL_TOKEN: AgB5HBBPMQMsGoTSpGIJjT/c6Zy33z4vZCvqwQ09ip1yp3ltU0P/2KE3zto/ikrE+hqSQyinBuzI6OwtV7+SOMNRx7ALETYy/RFKFmbfCLaPsk0USUAEpylyePWDHbPyf6RmVFa+QYODem8lZi6pGBXBrsY3sXzPtFs03btxhr8H9uT+x1RlOIkyXEtmv7VhO1laIy4ceG+RtXqYC4+VpcToHfYNOk5QgYB2yBjsEewx8j3DIP5d06fa4sq4YYjFCGPBJLHROwQmT5jqSPjXNjrykOgsJljOHmzzDaOUegIsfGMMC7X9AV6DahgXJan9KUc7zArvKZ1Z+E6VllNWvS7SwNzaqHLmccdgBcTIWw4pcyFe8ROadKNpSyKdY34zF+pxbO5T1acB1r3xsRcmxuNQ53Oh7m1uealERK2lO95w+7QhV3yN+HzitNSe5KRmtyqcyBFkaVC47urUy/airwZYSC0Y2JPLbYO9BWYeYMCHjoMDRBGaUAq1o9jdLRU3lfjP6XTf6foHtm+VRDGKjYfM6hWqGNHWh+dc5WQsFaMhDCl2bTZFgrHlbt7LUOav0QpryZG2kYusOCwHrJcaoZc2Y2E3vvPqj4HA3xTzGFhc+AsgVI98ggNu/l4BSXctAxPRuKHAoZ1lWOL0UFHAOiDtNeqDTg8eDVu6ECpWFlk9nuuqnFRWqaZwc5OUrzQ62UiXa0h+SSb+yCJXdgh+fw4gJrijI6fFsWxzHQE+zTLVA2MnCOlq/V3uRYiugQe2psGZsx2BB2DSU9zDhbe9QXyihXbEIsYzJ1pwPe1UIu2je0Naze19OMzTo4/7BbzsNyOa9n3r29MGqgzJJTHNPs598oydB34HhosGs9qwpIGnIuMB5AdZ89T2Y0EY3/5VgrCsp7Qflf7muLZXR6JwtpxehZns0A46egxq5lOE9kFB6VChd0UTaGXd
  template:
    metadata:
      creationTimestamp: null
      name: resume-builder-cloudflared-secret
      namespace: resume-builder
