---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: resume-builder-grafana-admin
  namespace: resume-builder
spec:
  encryptedData:
    admin-password: AgAYKwvLGBMj1qv30+CCptnO7FhA1mHZbA/D7wllmgYDLTKJtP9zZKF77qdmXCPYMn8UNVICba8OXNPwlMsH5wjjOrqZqFY7YnJyuXcTW8lmRM6h8wxrlOjVlo8oaUZVXfg4ZlvNZZYNcfbcz0pr0hSUPMxqZuv8Z5/2pn2CUz6h1m7QQ31D3T4pG9hN9IMgvnuCFCrZqUg00BqHko9j9h9xWoeyZ1u4i7VN+AARG4PRiQHbJBioADDUZSpH6l/KVhPFuXxofi+Co54UXowwCFuFsbNtVKCdtM5/gBupROT+vgw3/L400CAV3rtAwxUhkp5pS0MZ4TkZuLkpR/1VXVM9UHqn1/9ehXJccomz6FaLIvfSCXpQs8ZpCMFrGOtM1uuUe38Oz40ZoOK3E9YWZIF5bPxEykEVesce+370A/uXkUD0oYLh3XkCqS2l+C+/fqB8EggXoqVg8uE1EQ5iTmajmfbUhnPdVQcCXVJUpe+P+TOJulFX7ocANXH+7Ap+xOU5+IMP7nKYdACId3soSl1cxPyw2hJ7T0AiRKqWZEJUNgEWyzICxGUvseDtteXyf6miaD/HlzHDT0Mnitt+caDnxxsecX0KVt/qQNQjiHn7a3zrKuN7ImtoAyMs7cKeJq652GGiaAJqOulRgi58g7dGT29N9o4EdT0rvUGY7oJDOe0omLo4NIgKrU5cyG8GfohdAOTgqd/RZ6IvAiiRPcDnu0GwdgTV3lHSB+X5Hg29Lw==
    admin-user: AgCA11MnMePITd1x5itMOM05Pl74i8ephcXQCl3vdaKKywVLKIZRTPwG6jfzA3JtaDClWGd6fME6m8oWfAiyUwGtY7ypEECROdm2D0SfrRTbCFv0xxUiF8/WauolNyiEGaaoNTQOw+rIozYoPefBoQhMW+huztIF0mq7p79mFOa36DwCPbvhOEKhW+9Nwe+5JxxYYFCjEjKi91IgeNa+PR/8PDiRmk464dBLF3+me0JfzMU5ksPQA38Ux1RMDj2glLXvGrSzaz1cvpLN5VxizPZv+52WXkvQC+/wnn8mi2U1ja8AqnjBvZHar1PI7A72GFX1uz5fNdGOoSBVxjDJY/Qe+cb1M6+XftGslbWKIHB+Bg9twg9+8wquwD8lf5st9Tkxp5USZvxiYkHZmGqHSEqTGbHph1hoxn3HIyJtQSMB9k30znQJnOOZi2X0Z1CQ4W5q9sTkyR5rY9ns9wMoN97m+Q1tr0Oi4FEzlXQ49eqhKnOzhxn4qG6jjaqCz7+nz6C6fAaqKv4jX4H5ALiPk8e8+peRLXzRHcundZSjZLPG3KE3H/OKqTGI7uJBQMhIk3dVR85/IHnL1VE1wOVbaPWvOWp5glnZk+myvV+KDnEjzkx2R6+eIR+/z7pb1z06BuupnAYwnb/XPsE2G15/EFY1W+V6JKezhVlmKx57BDP4gpdVRoFXHmnHpzwFqwNLnNQpP0wrEw==
  template:
    metadata:
      creationTimestamp: null
      name: resume-builder-grafana-admin
      namespace: resume-builder
    type: Opaque
