apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "resume-builder.fullname" . }}-backend-sa
  annotations:
    # This role will be assumed by the pods using this ServiceAccount
    eks.amazonaws.com/role-arn: {{ .Values.backend.irsaRoleArn | quote }}