---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: argocd-notifications-secret
  namespace: argocd
spec:
  encryptedData:
    slack-webhook-url: AgBR6tBKlWQ372gR50UoS2jxkV9YmnU04lsUjszCb6vaTie11TDBpkgvhUHjsZh56Mdru2u62DLxXGRLb1DrieoLEQi4Rk9cZagBJRy09ii83nKKkiUiP2tLof4sszUKPyyGwCWhzI+lgLexGrC2uJtVQSTxm+6vt5+Gg/BHt2L09YNeSC5ReImofY89cPfmi6F9bYtOY0moAlqNXtEqGMqoWIQ2MmTvEF+EY/vZi8NdmIH3qdMBJxWwZHhxwylVBGK+vO8+2G4oyh6Pg5LvIllMS1R21sOh9yph30SSOvdRUFAqGbj8dxL+EmdUBTDjv533cSRDdF/C5Rlvx+mLHPnimHlG1n+KPjeD6yk0PEvz9mL8cJGqKHKQJDPDRUUAOnzPN+qSIE7ooL0TA0Xua/wrgMATyB8nktR9A6y/Fxl5+Du5QSmeIpfUSj//8lrjGi7JkYE8jdyLDr31UAaDso2L+bc87rXPbwKxNN3n79cRoq71jvumVscIM3fF98q69pgtv0C4UnILXajf7UpOXbpg33Q8S7cA673Dt105VuL6e8XuEQdBa02utqZ6pHa557vPgwAwsG+8n9GHEDq0f3yyyjIcJF5olIqNHdU3BWshp3JYTjmUJAcl76ZWzVny4JLBKL+axeHqlQTmUfCUuzL7O1gdj2oeMvCwO+BZfdWCMyg3XD32PXL5DJMIEjO5rDM6Bam9BK/KQKAulup4GzYUTv0aFwQP9+MWZc0MsCDgB9Wc/FF9Tg+IN2qU4NFj9w+QEeKPhDrbUiq4tbgtrvLp6tag/DDC6zSaTGQvJc0RZ9M=
  template:
    metadata:
      creationTimestamp: null
      name: argocd-notifications-secret
      namespace: argocd
    type: Opaque
